name: Deploy to GitHub Pages

on:
  push:
    branches: [v2]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm install
      - name: Debug packages
        run: |
          echo "Listing installed packages:"
          npm list || true
          echo "\nChecking node_modules directory:"
          ls -la node_modules/
          echo "\nChecking for specific packages:"
          ls -la node_modules/tailwindcss || echo "tailwindcss not found"
          ls -la node_modules/postcss || echo "postcss not found"
          ls -la node_modules/autoprefixer || echo "autoprefixer not found"

      - name: Build and Export
        run: npm run build

      - name: List out directory contents
        run: ls -la out

      - name: Verify build output
        run: |
          if [ ! -d "out" ]; then
            echo "Build failed: 'out' directory is missing"
            exit 1
          fi
          if [ ! -f "out/index.html" ]; then
            echo "Build failed: 'out/index.html' is missing"
            exit 1
          fi

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Prepare for deployment
        run: |
          # Create clean gh-pages directory
          rm -rf gh-pages
          mkdir gh-pages
          # Copy all files from out directory
          cp -r out/* gh-pages/
          # Ensure .nojekyll exists
          touch gh-pages/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: true